title: Welcome to Kaushi's reading station
description: >
  I'm a creative writer. Always like to learn something. 
  You can read all that is interesting in my words. Read my articles. 
  You can come up with your any idea & It's the result of my hard work
permalink: ':title/'
url: http://erandikaushalya.github.io
site-twitter:

# Author Settings
author: Kaushalya Pathirana # add your name
author-img: erandi.jpg # add your photo
about-author: >
  I'm a creative writer. Always like to learn something. You can read all that is interesting in my words. 
  Read my articles. You can come up with your any idea & It's the result of my hard work.
social-facebook: erandi.kaushalyaii
social-email: kaushalyaerandi773@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
fbcomments: yes